services:
  app-time2log-backend-prd:
    image: ghcr.io/time2logs/app-time2log/backend:latest
    container_name: app-time2log-backend-prd
    env_file: ./.env.prd
    expose:
      - "9080"
    networks:
      - time2log-net
    restart: unless-stopped

  app-time2log-frontend-prd:
    image: ghcr.io/time2logs/app-time2log/frontend:latest
    container_name: app-time2log-frontend-prd
    expose:
      - "80"
    networks:
      - time2log-net
    restart: unless-stopped

networks:
  time2log-net:
    external: true
