spring:
  application:
    name: app-time2log-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_AUTH_URL:anyplaceholderfortests}

supabase:
  url: ${SUPABASE_URL:anyplaceholderfortests}
  anon-key: ${SUPABASE_ANON_KEY:anyplaceholderfortests}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:anyplaceholderfortests}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:anyplaceholderfortests}

server:
  port: 9080
  shutdown: graceful

logging:
  level:
    root: INFO
    ch.time2log: INFO